#!/bin/sh
#
# spaceman-diff
# ...because you're too busy to leave the command line, dammit.
#
# Enjoy.

set -e

help()
{
  cat <<EOF
  This should normally be called via \`git-diff(1)\`.

  USAGE:
    spaceman-diff fileA shaA modeA fileB shaB modeB
EOF
}

if [ "$1" = "" ] ; then
  help
  exit
fi

fileNameA=$1
fileA=$2
shaA=$3
modeA=$4
fileB=$5
fileNameB=$5
shaB=$6
modeB=$7

# Header row
if [ -f "$fileA" ] ; then
  set +e
  sizeA=$(expr $(ls -l "$fileA" | awk '{print $5}') / 1024)
  set -e
else
  sizeA=0
fi

if [ -f "$fileB" ] ; then
  set +e
  sizeB=$(expr $(ls -l "$fileB" | awk '{print $5}') / 1024)
  set -e
else
  sizeB=0
fi

printf '\033[1;33m'"spaceman-diff a/$fileNameA b/$fileNameB\n"
if [ "$modeA" -ne "$modeB" ]
then
    printf '\033[1;33m'"old mode $modeA\n"
    printf '\033[1;33m'"new mode $modeB\n"
else
    mode=" $modeA"
fi
printf '\033[1;33m'"index ${shaA:0:8}..${shaB:0:8}${mode}\n"

printf '\033[1;35m'"@@ -${sizeA} kb +${sizeB} kb @@\n"

magick compare "$fileA" "$fileB" - | \
convert - jpg:- | \
jp2a --color --term-width -

